-- 资源应用表
CREATE TABLE TB_APP_RES
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    APP_CODE VARCHAR(36) NOT NULL COMMENT '业务系统编号',
    APP_NAME_CN VARCHAR(100) COMMENT '业务系统名',
    APP_PIC_LG VARCHAR(256) COMMENT 'APP大图',
    APP_PIC_SM VARCHAR(256) COMMENT 'APP小图',
    STATUS VARCHAR(1) COMMENT '0:无效， 1:有效',
    LOGIN_URL VARCHAR(256) COMMENT '业务系统登录url',
    APP_URL VARCHAR(256) COMMENT '业务系统首页url',
    ADMIN_USER_ID VARCHAR(36) COMMENT '业务管理用户ID',
    ADMIN_ROLE_ID VARCHAR(36) COMMENT '业务管理角色ID',
    ADMIN_WORK_ID VARCHAR(36) COMMENT '业务管理工作组ID',
    CREATE_TIME DATETIME COMMENT '创建时间',
    MEMO VARCHAR(150) COMMENT '备注'
);


-- 用户表
CREATE TABLE TB_USER
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    USER_NAME VARCHAR(50) COMMENT '姓名',
    SEX VARCHAR(2) COMMENT '性别',
    LOGIN_NAME VARCHAR(50) COMMENT '登录名',
    PASSWORD VARCHAR(50) COMMENT '密码',
    STATUS VARCHAR(1) COMMENT '0:无效， 1:有效',
    ID_CARD VARCHAR(18) COMMENT '身份证号',
    MOBILE VARCHAR(11) COMMENT '手机号',
    EMAIL VARCHAR(128) COMMENT '邮箱',
    PHOTO VARCHAR(256) COMMENT '头像',
    USER_CODE VARCHAR(30) COMMENT '职工编号',
    PROFESSION VARCHAR(128) COMMENT '职位',
    OFFICE_TEL VARCHAR(13) COMMENT '办公电话',
    CREATE_TIME DATETIME COMMENT '创建时间',
    MEMO VARCHAR(256) COMMENT '备注'
);

-- 业务资源用户表
CREATE TABLE TB_APP_USER
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    LOGIN_NAME VARCHAR(50) COMMENT '登录名',
    PASSWORD VARCHAR(50) COMMENT '密码',
    STATUS VARCHAR(1) COMMENT '0:无效， 1:有效',
    APPID VARCHAR(36) COMMENT '业务资源ID',
    USERID VARCHAR(36) COMMENT '用户ID',
    CREATE_TIME DATETIME COMMENT '创建时间',
    MEMO VARCHAR(256) COMMENT '备注'
);

-- 机构表
CREATE TABLE TB_ORG
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) COMMENT '机构名',
    ORG_CODE VARCHAR(20) COMMENT '部门编号',
    PARENT_ORG_CODE VARCHAR(20) COMMENT '父机构编号',
    XPATH VARCHAR(100) COMMENT '部门所在机构目录',
    MEMO VARCHAR(256) COMMENT '备注'
);

-- 机构用户表
CREATE TABLE TB_ORG_USER
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    ORG_ID VARCHAR(36) COMMENT '机构ID',
    USER_ID VARCHAR(36) COMMENT '用户ID'
);


-- 申请实例表
CREATE TABLE TB_APPLY_INSTANCE
(
    ID VARCHAR(38) PRIMARY KEY NOT NULL,
    SERVICE_TABLENAME VARCHAR(50) COMMENT '业务表名',
    SERVICE_PRIMARY_KEY VARCHAR(36) COMMENT '业务表ID',
    TEMPLATE_CODE VARCHAR(20) COMMENT '模板编码',
    APPLY_USER_ID VARCHAR(36) COMMENT '申请用户ID',
    APPLY_USER_NAME VARCHAR(50) COMMENT '申请用户名',
    CREATE_TIME DATETIME COMMENT '创建时间'
);

-- 申请当前活动表
CREATE TABLE TB_APPLY_ACTIVITY
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL,
    INSTANCE_ID VARCHAR(36) COMMENT '实例ID',
    ACTIVITY_NAME VARCHAR(50) COMMENT '当前环节名称',
    ACTIVITY_NAME_CN VARCHAR(150) COMMENT '当前环节中文名称',
    ASSIGNEE_ID VARCHAR(50) COMMENT '当前环节参与者ID',
    ASSIGNEE_NAME VARCHAR(50) COMMENT '当前环节参与者姓名',
    STATUS VARCHAR(20) COMMENT '0: 申请 1: 审核通过 2: 审核否决 3: 待审核',
    START_TIME DATETIME COMMENT '当前环节开始时间',
    OPINIONS VARCHAR(500) COMMENT '申请或审批意见',
    DUEDATE DATETIME COMMENT '处理时限'
);

-- 申请活动历史表
CREATE TABLE TB_APPLY_HIST
(
    ID VARCHAR(36) PRIMARY KEY NOT NULL COMMENT '主键',
    INSTANCE_ID VARCHAR(36) COMMENT '实例ID',
    ACTIVITY_NAME VARCHAR(50) COMMENT '当前环节名称',
    ACTIVITY_NAME_CN VARCHAR(50) COMMENT '当前环节中文名称',
    ASSIGNEE_ID VARCHAR(50) COMMENT '当前环节参与者ID',
    ASSIGNEE_NAME VARCHAR(50) COMMENT '当前环节参与者姓名',
    STATUS VARCHAR(20) COMMENT '0: 申请 1: 审核通过 2: 审核否决 3: 待审核',
    START_TIME DATETIME COMMENT '当前环节开始时间',
    END_TIME DATETIME COMMENT '环节结束时间',
    OPINIONS VARCHAR(500) COMMENT '申请或审批意见',
    DUEDATE DATETIME COMMENT '处理时限',
    NEXT_ACTIVITY_NAME VARCHAR(50) COMMENT '下一环节名称',
    ACTIVITY_STATUS VARCHAR(50) COMMENT '环节状态',
    STEP VARCHAR(20) COMMENT '当前环节步骤编号'
);